<div class="container my-5 py-5 z-depth-1 rounded">
  <section class="dark-grey-text">
    <div class="table-responsive">
      <table class="table product-table mb-0">
        <thead class="mdb-color lighten-5">
          <tr>
            <th></th>
            <th></th>
            <th class="font-weight-bold">
              <strong>Nom du film</strong>
            </th>
            <th></th>
            <th class="font-weight-bold">
              <strong>Prix unitaire</strong>
            </th>
            <th></th>
            <th class="font-weight-bold">
              <strong>Quantité</strong>
            </th>
            <th></th>
            <th class="font-weight-bold">
              <strong>Montant</strong>
            </th>
          </tr>
        </thead>
        <!-- /.Table head -->

        <!-- Table body -->
        <tbody>
          <?php
          $total = 0;
          $supertotal = 0;
          foreach ($this->panier as $value) { ?>
            <tr data-id="<?php echo $value['film']->id;?>"class="row_<?php echo $value['film']->id;?>">
              <td></td>
              <th scope="row">
                <?php
                $id = $value['film']->id_TMDb;
                $url =  'http://api.themoviedb.org/3/movie/'.$id.'?api_key=bf57f49ead0ced1ae34a5f0785d56290&language=fr-FR&append_to_response=query,videos,credits';
                $return = UTILS::searchTMDB($url);
                ?>
                <img src="https://www.themoviedb.org/t/p/w300_and_h450_bestv2<?php echo $return->poster_path; ?>" alt="" class="img-fluid z-depth-0">
              </th>
              <td>
                <a href="film?id=<?php echo $value['film']->id;?>">
                  <h5 class="mt-3">
                    <strong><?php echo $value['film']->name; ?></strong>
                  </h5>
                </a>
              </td>
              <td></td>
              <td>
                <strong><span class="price_<?php echo $value['film']->id;?>">
                  <?php echo $value['film']->price; ?> €
                </span></strong>
              </td>
              <td></td>
              <td>
                <strong><span class="quantity_<?php echo $value['film']->id;?>">
                  <?php echo $value['quantité'];?>
                </span></strong>
                <button data-id="<?php echo $value['film']->id;?>" id="remove_<?php echo $value['film']->id;?>" type="button" class="btn btn-sm blue-gradient btn-rounded fas fa-minus" data-toggle="tooltip" data-placement="top">
                </button>
                <button data-id="<?php echo $value['film']->id;?>" type="button" class="btn btn-sm blue-gradient btn-rounded fas fa-plus" data-toggle="tooltip" data-placement="top">
                </button>
              </td>
              <td></td>
              <?php
              $total = number_format(($value['film']->price * $value['quantité']),2);
              $supertotal =number_format(($supertotal + $total),2);?>
              <td class="font-weight-bold">
                <span class="total_<?php echo $value['film']->id;?>"><strong><?php echo $total;?></strong></span><strong> €</strong>
              </td>
            </tr>
          <?php
          } ?>
          <!-- Fourth row -->
          <tr>
            <td colspan="3"></td>
            <td>
              <h4 class="mt-2">
                <strong>Total</strong>
              </h4>
            </td>
            <td class="text-right">
              <h4 class="mt-2">
              <strong><span class="supertotal"><?php echo $supertotal;?></span></strong> <strong>€</strong>
              </h4>
            </td>
            <td colspan="3" class="text-right">
              <a href="/checkout">
                <button type="button" class="btn blue-gradient btn-rounded">Commander
                <i class="fas fa-angle-right right"></i>
                </button>
              </a>
            </td>
          </tr>
          <!-- Fourth row -->
        </tbody>
      </table>
    </div>
  </section>
</div>
<script type="text/javascript" src="<?php echo WEB_ROOT; ?>/javascripts/cartshopping.js"></script>