<div class="row">
    <div id="sort" class="col-md-2 list-group mt-5 pt-5">
        <li class="list-group-item list-group-item-action list-group-item-primary"><strong>Genre :</strong></li>
        <?php
        $row = 0;
            foreach ($this->categories as $value) {
                $row++;
                if($row&1){?>
                    <a data-genre="<?php echo $value->name; ?>" class="ajaxGenre list-group-item list-group-item-action list-group-item-dark text-center"><?php echo $value->name; ?></a>
            <?php
                }else{?>
                    <a data-genre="<?php echo $value->name; ?>" class="ajaxGenre list-group-item list-group-item-action text-center"><?php echo $value->name; ?></a>
                <?php
                }
            }?>
    </div>

    <div class="col-md-10 mt-3">
        <div id="search" class="row mb-2">
            <div class="col-md-10">
                <td style="width: 100%; text-align: center;">
                    <div class="az-letters text-center mt-2">
                        <p><strong>
                            <?php 
                            $letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '#'];
                            foreach ($letters as $value){?>
                                <a data-letter="<?php echo $value; ?>" class="ajaxLetter"><?php echo $value;?></a>
                            <?php
                            }?>
                        </strong></p>
                    </div>
                </td>
            </div>
            <div class="col-md-2 md-form my-0">
                <div class="form-inline row">
                    <input id="searchByTitle" name="searchByTitle" class="form-control ml-auto" type="text" placeholder="Cherchez un film" aria-label="Search">
                    <button id="buttonsearch" class="btn btn-inline-white btn-sm my-sm-0 ml-auto"><a class="ajaxTitle btn-floating btn-sm peach-gradient" type="button"><i class="fas fa-search"></i></a></button>
                </div>
            </div>
        </div>
        <div id="container_movies" class="row row-cols-1 row-cols-md-6">
            <?php
            foreach ($this->movies as $value) { ?>
                <div class="col mb-4">
                    <div class="card">
                        <div class="view overlay">
                            <?php
                            if ($value->poster_path != '') { ?>
                                <img src="https://www.themoviedb.org/t/p/w300_and_h450_bestv2<?php echo $value->poster_path; ?>" class="card-img-top" data-toggle="tooltip" data-placement="right">
                            <?php
                            } else { ?>
                                <img src="/images/covers/default.jpg" class="card-img-top" data-toggle="tooltip" data-placement="right">
                            <?php
                            } ?>
                            <a>
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>
                        <div class="card-body elegant-color white-text rounded-bottom">
                            <!-- Title -->
                            <h6 class="card-title"><?php echo $value->title; ?></h6>
                            <hr class="hr-light">
                            <!-- Text -->
                            <p class="card-text white-text mb-4">
                                <?php if (isset($value->release_date)) {
                                    echo UTILS::dateToFrench($value->release_date, 'j F Y');
                                } ?><br />
                            </p>
                            <!-- Link -->
                            <a href="/movie?id=<?php echo $value->id; ?>" class="white-text d-flex justify-content-end" id="tmdb_id" name="tmdb_id" data-tooltip="true">
                                <h7>Voir détails du film <i class="fas fa-angle-double-right"></i></h7>
                            </a>
                        </div>
                        <div class="rounded-bottom mdb-color text-center">
                            <p class="stars list-inline-item pr-2"><img class="tmdb" src="/images/logos/tmdb.svg"> <?php echo UTILS::showStars($value->vote_average); ?></p>
                        </div>

                    </div>
                </div>
            <?php
            } ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo WEB_ROOT; ?>/javascripts/searchbygenre.js"></script>
<script type="text/javascript" src="<?php echo WEB_ROOT; ?>/javascripts/searchbyletter.js"></script>
<script type="text/javascript" src="<?php echo WEB_ROOT; ?>/javascripts/searchbytitle.js"></script>