<nav id="navSearch" class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline ml-auto" id="formdbtv" action="/tmdb" method="POST">
            <div class="md-form my-0">
                <input id="searchByTitle" name="searchByTitle" class="form-control" type="text" placeholder="Cherchez un film" aria-label="Search">
                <button id="buttonsearch" class="btn btn-inline-white btn-sm my-sm-0 ml-auto"><a class="btn-floating btn-sm peach-gradient" type="button"><i class="fas fa-search"></i></a></button>
            </div>
        </form>
    </div>
</nav>

<div id="container_tvdb" class="row row-cols-1 row-cols-md-6">
    <?php
    if(isset($this->return->results)){
        foreach($this->return->results as $value){?>
            <div class="col mb-4">
                <div class="card">
                    <div class="view overlay">
                        <?php
                        if($value->poster_path != ''){?>
                            <img src="https://www.themoviedb.org/t/p/w300_and_h450_bestv2<?php echo $value->poster_path; ?>" class="card-img-top" data-toggle="tooltip" data-placement="right">
                        <?php
                        }else{?>
                            <img src="/images/covers/default.jpg" class="card-img-top" data-toggle="tooltip" data-placement="right">
                        <?php
                        }?>
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <div class="card-body elegant-color white-text rounded-bottom">
                        <!-- Title -->
                        <h6 class="card-title"><?php echo $value->title; ?></h6>
                        <hr class="hr-light">
                        <!-- Text -->
                        <p class="card-text white-text mb-4">
                            <?php if(isset($value->release_date)){
                                echo UTILS::dateToFrench($value->release_date, 'j F Y'); 
                            }?><br />
                        </p>
                        <!-- Link -->
                        <a href="/tmdb_view?id_TMDb=<?php echo $value->id; ?>" class="white-text d-flex justify-content-end" id="tmdb_id" name="tmdb_id" data-tooltip="true">
                            <h7>Voir détails du film <i class="fas fa-angle-double-right"></i></h7>
                        </a>
                    </div>
                    <div class="rounded-bottom mdb-color text-center">
                            <p class="stars list-inline-item pr-2"><img class="tmdb" src="/images/logos/tmdb.svg"> <?php echo UTILS::showStars($value->vote_average); ?></p>
                    </div>

                </div>
            </div>
        <?php
        }
    }?>
</div>