<!--Modal: modalYT-->
<div class="modal fade" id="modalYT" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Body-->
            <div class="modal-body mb-0 p-0">
                <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
                    <iframe class="embed-responsive-item" src="<?php foreach ($this->return->videos->results as $value) {
                                                                    if (isset($value->type) && $value->type == 'Trailer') {
                                                                        //echo 'https://www.youtube.com/embed/' . $value->key;
                                                                    }
                                                                } ?>" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>