<!-- Footer -->
<footer class="page-footer font-small indigo" id="footer">
    <!-- Footer Links -->
    <div class="container">

        <!-- Grid row-->
        <div class="row text-center d-flex justify-content-center pt-3 mb-2">

            <!-- Grid column -->
            <div class="col-md-2 mb-2">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!">About us</a>
                </h6>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-2">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!">Products</a>
                </h6>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-2">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!">Awards</a>
                </h6>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-2">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!">Help</a>
                </h6>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-2">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!">Contact</a>
                </h6>
            </div>
        </div>

        <!-- Grid row-->
        <div class="row pb-2">

            <!-- Grid column -->
            <div class="col-md-12">

                <div class="mb-2 flex-center">

                    <!-- Facebook -->
                    <a class="fb-ic">
                        <i class="fab fa-facebook-f fa-lg white-text mr-4"> </i>
                    </a>
                    <!-- Twitter -->
                    <a class="tw-ic">
                        <i class="fab fa-twitter fa-lg white-text mr-4"> </i>
                    </a>
                    <!-- Google +-->
                    <a class="gplus-ic">
                        <i class="fab fa-google-plus-g fa-lg white-text mr-4"> </i>
                    </a>
                    <!--Linkedin -->
                    <a class="li-ic">
                        <i class="fab fa-linkedin-in fa-lg white-text mr-4"> </i>
                    </a>
                    <!--Instagram-->
                    <a class="ins-ic">
                        <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
                    </a>
                    <!--Pinterest-->
                    <a class="pin-ic">
                        <i class="fab fa-pinterest fa-lg white-text"> </i>
                    </a>

                </div>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row-->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-2">© 2022 Copyright:
        <a href="https://jesaispastelecharger.fr/"> JeSaisPasTelecharger.fr</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->