<div class="modal fade" id="modalLoginRegister" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog cascading-modal" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Modal cascading tabs-->
            <div class="modal-c-tabs">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs md-tabs tabs-2 light-blue darken-3" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#panel7" role="tab"><i class="fas fa-user mr-1"></i>
                            Connexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#panel8" role="tab"><i class="fas fa-user-plus mr-1"></i>
                            Inscription</a>
                    </li>
                </ul>

                <!-- Tab panels -->
                <div class="tab-content">
                    <!--Panel 7-->
                    <div class="tab-pane fade in show active" id="panel7" role="tabpanel">

                        <!--Body-->
                        <div class="modal-body mb-1" id="loginUser">
                            <form method='POST' action="<?php echo WEB_ROOT; ?>/accueil" id="loginForm" class="needs-validation" .was-validated>

                                <div class="md-form form-sm text-center mb-3">
                                    <div class="wp-social-login-widget">
                                        <div class="wp-social-login-connect-with">Connectez-vous avec:</div>
                                        <div class="wp-social-login-provider-list">
                                            <a rel="nofollow" href="" title="Connect with Facebook" class="fb-ic mr-3"  data-provider="Facebook" role="button"><i class="fab fa-lg fa-facebook-f"></i></a>
                                            <a rel="nofollow" href="" title="Connect with Twitter" class="tw-ic mr-3" data-provider="Twitter" role="button"><i class="fab fa-lg fa-twitter"></i></a>
                                            <a rel="nofollow" href="" title="Connect with Google" class="gplus-ic mr-3" data-provider="Google" role="button"><i class="fab fa-lg fa-google"></i></a>
                                        </div>
                                    </div>
                                </div>

                                <p class="text-center">ou:</p>

                                <div class="md-form form-sm mb-5">
                                    <i class="fas fa-user prefix"></i>
                                    <input type="text" id="login" name="login" class="form-control form-control-sm validate">
                                    <label data-error="wrong" data-success="right" for="login">Nom d'utilisateur</label>
                                </div>

                                <div class="md-form form-sm mb-4">
                                    <i class="fas fa-lock prefix"></i>
                                    <input type="password" id="pwd" name="pwd" class="form-control form-control-sm validate">
                                    <label data-error="wrong" data-success="right" for="pwd">Mot de passe</label>
                                </div>
                                <div class="text-center mt-2">
                                    <button class="btn blue-gradient btn-rounded">Se connecter<i class="fas fa-sign-in ml-1" id="loginSubmit" name="loginSubmit"></i></button>
                                </div>
                            </form>
                        </div>
                        <!--Footer-->
                        <div class="modal-footer">
                            <div class="options text-center text-md-right mt-1">
                                <p><a href="#" class="blue-text">Mot de passe oublié</a></p>
                            </div>
                            <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Fermer</button>
                        </div>

                    </div>
                    <!--/.Panel 7-->

                    <!--Panel 8-->
                    <div class="tab-pane fade" id="panel8" role="tabpanel">

                        <!--Body-->
                        <div class="modal-body" id="registerUser">
                            <form method='POST' enctype="multipart/form-data" action="<?php echo WEB_ROOT; ?>/accueil" id="registerForm" class="cmx-form needs-validation" novalidate>
                                <div class="md-form form-sm mb-5">
                                    <div class="file-field">
                                        <div class="file-upload-wrapper mb-4 text-center">
                                            <input type="file" id="input-file-now" class="file-upload">
                                                <img src="<?php echo WEB_ROOT; ?>/images/users/default.webp" class="rounded-circle z-depth-1-half avatar-pic" alt="example placeholder avatar">
                                            </input>
                                        </div>
                                        <div class="d-flex justify-content-center">
                                            <div class="btn btn-mdb-color btn-rounded float-left">
                                                <span>Ajouter un avatar (optionel)</span>
                                                <input type="hidden" name="MAX_FILE_SIZE" value="20000000000" />
                                                <input type="file" id="registerAvatar" name="registerAvatar">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="md-form form-sm mb-5">
                                    <i class="fas fa-user prefix"></i>
                                    <input type="text" id="registerLogin" name="registerLogin" class="form-control form-control-sm" required="" autofocus="">
                                    <label for="registerLogin">Nom d'utilisateur</label>
                                    <small id="output_registerLogin" class="mt-1"></small>
                                </div>

                                <div class="md-form form-sm mb-5">
                                    <i class="fas fa-envelope prefix"></i>
                                    <input type="email" id="registerMail" name="registerMail" class="form-control form-control-sm" required="" autofocus="">
                                    <label for="registerMail">Adresse email</label>
                                    <small id="output_registerMail" class="mt-1"></small>

                                <div class="md-form form-sm mb-5">
                                    <i class="fas fa-lock prefix"></i>
                                    <input type="password" id="registerPwd" name="registerPwd" class="form-control form-control-sm" required="" autofocus="">
                                    <label for="registerPwd">Mot de passe</label>
                                    <small id="output_registerPwd" class="mt-1"></small>

                                <div class="md-form form-sm mb-4">
                                    <i class="fas fa-lock prefix"></i>
                                    <input type="password" id="registerChkPwd" name="registerChkPwd" class="form-control form-control-sm" required="" autofocus="">
                                    <label for="registerChkPwd">Répétez le mot de passe</label>
                                    <small id="output_registerChkPwd" class="mt-1"></small>

                                <div class="form-group mt-4">
                                    <input class="form-check-input" type="checkbox" id="registerAgree" name="registerAgree" required="" autofocus="">
                                    <label for="registerAgree" class="black-text form-check-label">Veuillez accepter les<a href="#" class="green-text font-weight-bold"> conditions d'utilisation</a></label>
                                </div>

                                <div class="text-center form-sm mt-2">
                                    <small id="status" class="mt-1"></small>
                                    <button class="btn blue-gradient btn-rounded" id="registerSubmit" name="registerSubmit" disabled value="true">S'inscrire<i id="registerSubmit" name="registerSubmit" class="fas fa-sign-in ml-1"></i></button>
                                </div>
                            </form>
                        </div>
                        <!--Footer-->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                    <!--/.Panel 8-->
                </div>
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>
<script type="text/javascript" src="<?php echo WEB_ROOT; ?>/javascripts/checkregister.js"></script>