<div class="modal fade" id="modalContact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container my-5">
    <!--Section: Content-->
    <section class="contact-section dark-grey-text mb-5">
      <style>
        .contact-section .form .btn-floating {
          left: 3px;
        }
      </style>
      <!-- Form with header -->
      <div class="card">
        <!-- Grid row -->
        <div class="row">
          <!-- Grid column -->
          <div class="col-lg-8">
            <div class="card-body form">
              <!-- Header -->
              <h3 class="font-weight-bold dark-grey-text mt-4"><i class="fas fa-envelope pr-2 mr-1"></i>Nous écrire:</h3>
              <!-- Grid row -->
              <div class="row">
                <!-- Grid column -->
                <div class="col-md-6">
                  <div class="md-form mb-0">
                    <input type="text" id="form-contact-name" class="form-control">
                    <label for="form-contact-name" class="">Nom</label>
                  </div>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-6">
                  <div class="md-form mb-0">
                    <input type="text" id="form-contact-email" class="form-control">
                    <label for="form-contact-email" class="">Email</label>
                  </div>
                </div>
                <!-- Grid column -->
              </div>
              <!-- Grid row -->
              <!-- Grid row -->
              <div class="row">
                <!-- Grid column -->
                <div class="col-md-6">
                  <div class="md-form mb-0">
                    <input type="text" id="form-contact-phone" class="form-control">
                    <label for="form-contact-phone" class="">Téléphone</label>
                  </div>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-6">
                  <div class="md-form mb-0">
                    <input type="text" id="form-contact-company" class="form-control">
                    <label for="form-contact-company" class="">N° de commande (facultatif)</label>
                  </div>
                </div>
                <!-- Grid column -->
              </div>
              <!-- Grid row -->
              <!-- Grid row -->
              <div class="row">
                <!-- Grid column -->
                <div class="col-md-12">
                  <div class="md-form mb-0">
                    <textarea id="form-contact-message" class="form-control md-textarea" rows="3"></textarea>
                    <label for="form-contact-message">Votre message</label>
                    <a class="btn-floating btn-lg blue">
                      <i class="far fa-paper-plane"></i>
                    </a>
                  </div>
                </div>
                <!-- Grid column -->
              </div>
              <!-- Grid row -->
            </div>

          </div>
          <!-- Grid column -->
          <!-- Grid column -->
          <div class="col-lg-4">
            <div class="card-body contact text-center h-100 white-text">
              <h3 class="font-weight-bold my-4 pb-2">Nous contacter</h3>
              <ul class="text-lg-left list-unstyled ml-4">
                <li>
                  <p><i class="fas fa-map-marker-alt pr-2"></i>ZAC du warez, 94126, CODECS</p><br />
                </li>
                <li>
                  <p><i class="fas fa-phone pr-2"></i>+33 (0)1 23 45 67 89</p><br />
                </li>
                <li>
                  <p><i class="fas fa-envelope pr-2"></i>contact@example.com</p><br />
                </li>
              </ul>
              <hr class="hr-light my-4">
              <ul class="list-inline text-center list-unstyled">
                <li class="list-inline-item">
                  <a class="p-2 fa-lg tw-ic">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="p-2 fa-lg li-ic">
                    <i class="fab fa-linkedin-in"> </i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="p-2 fa-lg ins-ic">
                    <i class="fab fa-instagram"> </i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
      <!-- Form with header -->
    </section>
    <!--Section: Content-->
  </div>
</div>